import video1 from "../assets/video1.png"
import video2 from "../assets/video3.png"
import video3 from "../assets/video4.png"
import video4 from "../assets/video2.jpg"
import video5 from "../assets/video5.jpg"
const videoData = [
  // // --- Original 6 Entries ---
  // {
  //   id: 1,
  //   imageUrl: video1,
  //   title: "Healthy Living, Happier Life.",
  //   description: "Learn simple habits that boost your health and happiness every day.",
  //   videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4", // working sample video
  // },
  // {
  //   id: 2,
  //   imageUrl: video2,
  //   title: "Finding Balance in a Busy World.",
  //   description: "Tips and tricks to maintain mental balance despite a hectic schedule.",
  //   videoUrl: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
  // },
  // {
  //   id: 3,
  //   imageUrl: video3,
  //   title: "Small Steps to Big Fitness Wins.",
  //   description: "How tiny daily actions can lead to major improvements in fitness.",
  //   videoUrl: "https://www.w3schools.com/html/movie.mp4",
  // },
  // {
  //   id: 4,
  //   imageUrl: video4,
  //   title: "The Power of Mindful Nutrition.",
  //   description: "Discover mindful eating habits that transform your energy and mood.",
  //   videoUrl: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
  // },
  // {
  //   id: 5,
  //   imageUrl:video5,
  //   title: "Small Steps to Big Fitness Wins (Part 2).",
  //   description: "Simple strategies for consistent fitness progress.",
  //   videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  // },
  // {
  //   id: 6,
  //   imageUrl: "https://images.unsplash.com/photo-1607746882042-944635dfe10e?auto=format&fit=crop&w=600&q=80",
  //   title: "The Power of Mindful Nutrition (Deep Dive).",
  //   description: "Practical advice for improving diet and well-being.",
  //   videoUrl: "https://www.w3schools.com/html/movie.mp4",
  // },
  // // --- 44 New Synthetic Entries (7-50) ---
  // {
  //   id: 7,
  //   imageUrl: "https://images.unsplash.com/photo-1607746882042-944635dfe10e?auto=format&fit=crop&w=600&q=80",
  //   title: "A Week in Kyoto: Temples and Traditions.",
  //   description: "Experience the timeless beauty of Japan's ancient capital in this travel vlog.",
  //   videoUrl: "https://www.w3schools.com/html/movie.mp4",
  // },
  // {
  //   id: 8,
  //   imageUrl: "https://images.unsplash.com/photo-1607746882042-944635dfe10e?auto=format&fit=crop&w=600&q=80",
  //   title: "Mastering React Hooks in 15 Minutes.",
  //   description: "A quick tutorial covering useState, useEffect, and custom hooks for React developers.",
  //   videoUrl: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
  // },
  // {
  //   id: 9,
  //   imageUrl: "https://placehold.co/600x400/14b8a6/ffffff?text=Cooking+Skills",
  //   title: "The Perfect Sourdough Starter: Step-by-Step.",
  //   description: "Guide to culturing and maintaining a vigorous sourdough starter at home.",
  //   videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  // },
  // {
  //   id: 10,
  //   imageUrl: "https://placehold.co/600x400/374151/ffffff?text=Space+Science",
  //   title: "Journey to Mars: The Engineering Challenges.",
  //   description: "Documentary exploring the logistics and technological hurdles of sending humans to Mars.",
  //   videoUrl: "https://www.w3schools.com/html/movie.mp4",
  // },
  // {
  //   id: 11,
  //   imageUrl: "https://placehold.co/600x400/ef4444/ffffff?text=Meditation",
  //   title: "Morning Meditation for Clarity and Focus.",
  //   description: "Guided session to start your day with calm and sharp mental clarity.",
  //   videoUrl: "https://sample-videos.com/video123/mp4/480/big_buck_bunny_480p_1mb.mp4",
  // },
  // {
  //   id: 12,
  //   imageUrl: "https://placehold.co/600x400/4f46e5/ffffff?text=Digital+Art",
  //   title: "Procreate Tutorial: Painting Realistic Skies.",
  //   description: "Advanced techniques for digital artists using the Procreate app.",
  //   videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  // },
  // {
  //   id: 13,
  //   imageUrl: "https://placehold.co/600x400/65a30d/ffffff?text=Gardening",
  //   title: "Hydroponics for Beginners: Grow Anything Indoors.",
  //   description: "An introduction to soilless growing systems for apartment dwellers.",
  //   videoUrl: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
  // },
  // {
  //   id: 14,
  //   imageUrl: "https://placehold.co/600x400/ca8a04/ffffff?text=Finance",
  //   title: "Index Funds Explained: Passive Investing Strategy.",
  //   description: "Understanding how to build long-term wealth using low-cost index funds.",
  //   videoUrl: "https://www.w3schools.com/html/movie.mp4",
  // },
  // {
  //   id: 15,
  //   imageUrl: "https://placehold.co/600x400/db2777/ffffff?text=Home+Decor",
  //   title: "Minimalist Home Organization Hacks.",
  //   description: "Simple, beautiful ways to declutter and organize your living space.",
  //   videoUrl: "https://sample-videos.com/video123/mp4/480/big_buck_bunny_480p_1mb.mp4",
  // },
  // {
  //   id: 16,
  //   imageUrl: "https://placehold.co/600x400/0f766e/ffffff?text=Photography",
  //   title: "Luminosity Masks: Advanced Photo Editing.",
  //   description: "Tutorial on using advanced masking techniques in Adobe Photoshop.",
  //   videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  // },
  // {
  //   id: 17,
  //   imageUrl: "https://placehold.co/600x400/be185d/ffffff?text=Language",
  //   title: "10 Essential Phrases for Italian Travel.",
  //   description: "Learn key phrases and cultural tips for your trip to Italy.",
  //   videoUrl: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
  // },
  // {
  //   id: 18,
  //   imageUrl: "https://placehold.co/600x400/6d28d9/ffffff?text=History",
  //   title: "The Silk Road: A History of Global Trade.",
  //   description: "Exploration of the ancient routes that connected East and West.",
  //   videoUrl: "https://www.w3schools.com/html/movie.mp4",
  // },
  // {
  //   id: 19,
  //   imageUrl: "https://placehold.co/600x400/0e7490/ffffff?text=Software+Review",
  //   title: "Top 5 Productivity Apps for Developers.",
  //   description: "Reviews of tools to maximize efficiency in your coding workflow.",
  //   videoUrl: "https://sample-videos.com/video123/mp4/480/big_buck_bunny_480p_1mb.mp4",
  // },
  // {
  //   id: 20,
  //   imageUrl: "https://placehold.co/600x400/92400e/ffffff?text=Woodworking",
  //   title: "Building a Minimalist Desk: DIY Project.",
  //   description: "A step-by-step guide to constructing a modern, sturdy wooden desk.",
  //   videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  // },
  // {
  //   id: 21,
  //   imageUrl: "https://placehold.co/600x400/fbbf24/000000?text=AstroPhysics",
  //   title: "Black Holes Explained: What We Know and Don't Know.",
  //   description: "An accessible breakdown of the science behind black holes and event horizons.",
  //   videoUrl: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
  // },
  // {
  //   id: 22,
  //   imageUrl: "https://placehold.co/600x400/1e40af/ffffff?text=Personal+Growth",
  //   title: "Overcoming Procrastination: The 5-Minute Rule.",
  //   description: "Simple, science-backed technique to break the habit of putting things off.",
  //   videoUrl: "https://www.w3schools.com/html/movie.mp4",
  // },
  // {
  //   id: 23,
  //   imageUrl: "https://placehold.co/600x400/84cc16/ffffff?text=Hiking",
  //   title: "The Ultimate Guide to Backpacking Gear.",
  //   description: "Review of essential lightweight equipment for multi-day hikes.",
  //   videoUrl: "https://sample-videos.com/video123/mp4/480/big_buck_bunny_480p_1mb.mp4",
  // },
  // {
  //   id: 24,
  //   imageUrl: "https://placehold.co/600x400/c026d3/ffffff?text=Art+Theory",
  //   title: "Understanding Color Theory: The Artist's Secret Weapon.",
  //   description: "A deep dive into the color wheel, harmony, and contrast.",
  //   videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  // },
  // {
  //   id: 25,
  //   imageUrl: "https://placehold.co/600x400/059669/ffffff?text=Data+Science",
  //   title: "Introduction to Machine Learning with Python.",
  //   description: "First part of a series covering basic algorithms and data preparation.",
  //   videoUrl: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
  // },
  // {
  //   id: 26,
  //   imageUrl: "https://placehold.co/600x400/7c3aed/ffffff?text=Music+Production",
  //   title: "Mixing Vocals: Achieving a Professional Sound.",
  //   description: "Techniques for compression, EQ, and reverb on lead vocals in a DAW.",
  //   videoUrl: "https://www.w3schools.com/html/movie.mp4",
  // },
  // {
  //   id: 27,
  //   imageUrl: "https://placehold.co/600x400/dc2626/ffffff?text=History+Facts",
  //   title: "Unraveling the Mysteries of Ancient Egypt.",
  //   description: "Exploring the Pharaohs, pyramids, and cultural legacy of one of the world's oldest civilizations.",
  //   videoUrl: "https://sample-videos.com/video123/mp4/480/big_buck_bunny_480p_1mb.mp4",
  // },
  // {
  //   id: 28,
  //   imageUrl: "https://placehold.co/600x400/475569/ffffff?text=Car+Repair",
  //   title: "Basic Car Maintenance You Can Do Yourself.",
  //   description: "How to check fluids, change wipers, and inspect tires like a pro.",
  //   videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  // },
  // {
  //   id: 29,
  //   imageUrl: "https://placehold.co/600x400/6366f1/ffffff?text=Science+Experiments",
  //   title: "Making Invisible Ink at Home: Fun Science.",
  //   description: "Simple and safe chemistry experiment for kids and curious adults.",
  //   videoUrl: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
  // },
  // {
  //   id: 30,
  //   imageUrl: "https://placehold.co/600x400/0d9488/ffffff?text=Entrepreneur",
  //   title: "Launching a Startup: From Idea to Funding.",
  //   description: "Advice on creating a business plan, securing seed money, and building a minimum viable product.",
  //   videoUrl: "https://www.w3schools.com/html/movie.mp4",
  // },
  // {
  //   id: 31,
  //   imageUrl: "https://placehold.co/600x400/d97706/ffffff?text=Stock+Market",
  //   title: "Understanding Options Trading for Beginners.",
  //   description: "A comprehensive guide to call and put options and risk management.",
  //   videoUrl: "https://sample-videos.com/video123/mp4/480/big_buck_bunny_480p_1mb.mp4",
  // },
  // {
  //   id: 32,
  //   imageUrl: "https://placehold.co/600x400/f87171/ffffff?text=Yoga+Flow",
  //   title: "30-Minute Vinyasa Flow for Stress Relief.",
  //   description: "Follow along with this intermediate yoga routine focusing on breath and movement.",
  //   videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  // },
  // {
  //   id: 33,
  //   imageUrl: "https://placehold.co/600x400/9ca3af/ffffff?text=DIY+Electronics",
  //   title: "Arduino Project: Building a Smart Plant Monitor.",
  //   description: "Instructions for programming an Arduino to monitor soil moisture and temperature.",
  //   videoUrl: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
  // },
  // {
  //   id: 34,
  //   imageUrl: "https://placehold.co/600x400/5b21b6/ffffff?text=Philosophy",
  //   title: "Stoicism for Modern Life: Finding Inner Peace.",
  //   description: "Applying ancient Stoic practices like mindfulness and acceptance to daily stress.",
  //   videoUrl: "https://www.w3schools.com/html/movie.mp4",
  // },
  // {
  //   id: 35,
  //   imageUrl: "https://placehold.co/600x400/0891b2/ffffff?text=Photography+Gear",
  //   title: "Full Frame vs. Crop Sensor: Which Camera is Right?",
  //   description: "Detailed comparison of camera sensor technologies for aspiring photographers.",
  //   videoUrl: "https://sample-videos.com/video123/mp4/480/big_buck_bunny_480p_1mb.mp4",
  // },
  // {
  //   id: 36,
  //   imageUrl: "https://placehold.co/600x400/44403c/ffffff?text=Barbecue",
  //   title: "Smoking Ribs: Texas Style BBQ Masterclass.",
  //   description: "The secrets to perfectly tender and flavorful smoked pork ribs.",
  //   videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  // },
  // {
  //   id: 37,
  //   imageUrl: "https://placehold.co/600x400/ec4899/ffffff?text=Psychology",
  //   title: "The Halo Effect: Understanding Cognitive Bias.",
  //   description: "Exploring how first impressions unfairly influence our overall judgments of others.",
  //   videoUrl: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
  // },
  // {
  //   id: 38,
  //   imageUrl: "https://placehold.co/600x400/10b981/ffffff?text=Web+Design",
  //   title: "Responsive Design with Tailwind CSS.",
  //   description: "Tutorial on building flexible, mobile-first layouts using the utility-first CSS framework.",
  //   videoUrl: "https://www.w3schools.com/html/movie.mp4",
  // },
  // {
  //   id: 39,
  //   imageUrl: "https://placehold.co/600x400/2563eb/ffffff?text=Book+Review",
  //   title: "Review: 'Sapiens: A Brief History of Humankind'.",
  //   description: "A summary and critical analysis of Yuval Noah Harari's acclaimed non-fiction work.",
  //   videoUrl: "https://sample-videos.com/video123/mp4/480/big_buck_bunny_480p_1mb.mp4",
  // },
  // {
  //   id: 40,
  //   imageUrl: "https://placehold.co/600x400/a855f7/ffffff?text=Astronomy",
  //   title: "The James Webb Space Telescope's Biggest Discoveries.",
  //   description: "Highlights and analysis of the groundbreaking images and data from the JWST.",
  //   videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  // },
  // {
  //   id: 41,
  //   imageUrl: "https://placehold.co/600x400/eab308/000000?text=Financial+News",
  //   title: "2024 Market Outlook: Key Trends to Watch.",
  //   description: "Expert analysis on projected economic shifts and investment opportunities.",
  //   videoUrl: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
  // },
  // {
  //   id: 42,
  //   imageUrl: "https://placehold.co/600x400/030712/ffffff?text=Game+Design",
  //   title: "Level Design Fundamentals for Indie Developers.",
  //   description: "Principles for creating engaging and balanced game environments.",
  //   videoUrl: "https://www.w3schools.com/html/movie.mp4",
  // },
  // {
  //   id: 43,
  //   imageUrl: "https://placehold.co/600x400/f43f5e/ffffff?text=Pet+Care",
  //   title: "Training Your Puppy: Essential Commands.",
  //   description: "Positive reinforcement techniques for teaching your dog basic obedience.",
  //   videoUrl: "https://sample-videos.com/video123/mp4/480/big_buck_bunny_480p_1mb.mp4",
  // },
  // {
  //   id: 44,
  //   imageUrl: "https://placehold.co/600x400/15803d/ffffff?text=Electric+Cars",
  //   title: "EV Battery Tech: The Next Breakthroughs.",
  //   description: "Reviewing solid-state batteries and other innovations driving the electric vehicle market.",
  //   videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  // },
  // {
  //   id: 45,
  //   imageUrl: "https://placehold.co/600x400/a3e635/000000?text=Home+Maintenance",
  //   title: "Fixing Common Plumbing Leaks: DIY.",
  //   description: "Simple repairs for leaky faucets and pipes, saving you money on plumbers.",
  //   videoUrl: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
  // },
  // {
  //   id: 46,
  //   imageUrl: "https://placehold.co/600x400/78716c/ffffff?text=Film+Analysis",
  //   title: "Decoding Christopher Nolan's Use of Time.",
  //   description: "An in-depth analysis of narrative structure in Nolan's films like *Inception* and *Tenet*.",
  //   videoUrl: "https://www.w3schools.com/html/movie.mp4",
  // },
  // {
  //   id: 47,
  //   imageUrl: "https://placehold.co/600x400/fb923c/ffffff?text=Career+Advice",
  //   title: "Interview Skills: Answering Behavioral Questions.",
  //   description: "Using the STAR method to ace tough questions in job interviews.",
  //   videoUrl: "https://sample-videos.com/video123/mp4/480/big_buck_bunny_480p_1mb.mp4",
  // },
  // {
  //   id: 48,
  //   imageUrl: "https://placehold.co/600x400/94a3b8/ffffff?text=Travel+Guides",
  //   title: "The Hidden Gems of Patagonia.",
  //   description: "A comprehensive guide to hiking and exploring the stunning landscapes of Southern Chile and Argentina.",
  //   videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  // },
  // {
  //   id: 49,
  //   imageUrl: "https://placehold.co/600x400/f472b6/ffffff?text=Software+Testing",
  //   title: "Unit Testing with Jest and Enzyme.",
  //   description: "A tutorial on setting up and writing effective tests for modern JavaScript applications.",
  //   videoUrl: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
  // },
  // {
  //   id: 50,
  //   imageUrl: "https://placehold.co/600x400/1c1917/ffffff?text=Creative+Writing",
  //   title: "World Building 101: Creating Believable Fantasy Worlds.",
  //   description: "Techniques for developing compelling cultures, histories, and magic systems for fiction.",
  //   videoUrl: "https://www.w3schools.com/html/movie.mp4",
  // },
];

export default videoData;